### ISSUE TITLE
Doesn't work with GoogleTranslate

### ISSUE THREAD

**Issue by edwinlimlx** [parsable/react-truncate-markup#65] opened 2020-12-03 02:48 UTC
Hi, 

Thanks for the amazing plugin!
However we have an issue when Chrome's Google Translate is being used. 

Reproducible here https://clx8h.csb.app/ (Source: https://codesandbox.io/s/react-truncate-markup-google-translate-clx8h)

The root caused seems to be deriving from https://github.com/facebook/react/issues/11538#issuecomment-390386520 Not sure if there's a fix for this?

**Comment by singleseeker** [comment] 2021-01-09 07:06
Any update?

**Comment by patrik-piskay** [comment] 2021-01-09 18:25
Unfortunately I am not able to do much here as it's a Google Translate issue. I tried out wrapping both the content and ellipsis in `span`s (as suggested as a possible workaround) and that worked in terms of actually rendering something in Google Translate, but I won't be adding that to the library as it adds unnecessary/potentially unwanted HTML tags into the page, potentially breaking styling. 
But it's something users can do themselves for both the content and ellipsis (`ellipsis` prop) if they want to.

Another solution for the time being (until the issue is fixed by GT team) would be ignoring these errors by monkeypatching `removeChild`/`insertBefore` https://github.com/facebook/react/issues/11538#issuecomment-417504600

**Closed by patrik-piskay** 2021-01-09 18:25 UTC
