### ISSUE TITLE
White page upon using the translate functionality in the browser.

### ISSUE THREAD

**Issue by smirceamihai** [parsable/react-truncate-markup#57] opened 2020-09-02 10:53 UTC
Hei,

Upon using the translate functionality of the browser (Right click - Translate to..) then:
- Page is emptied of content
- Following exception is thrown: 'DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node'

BROWSER
Chrome

EXAMPLE
https://react-truncate-markup.patrik-piskay.now.sh/

**Comment by edwinlimlx** [comment] 2020-09-23 06:34
Having same issue. @smirceamihai did you manage to fix it?

**Comment by jandom** [comment] 2020-09-23 12:31
Same here

**Comment by smirceamihai** [comment] 2020-09-23 13:17
Hei @edwinlimlx,
The benefits that this component is offering us are far too low in order for us to start debugging the root cause.
We've implemented a (temporary) pure CSS solution (based on Bootstrap) which looks ok in all major browsers.

**Comment by patrik-piskay** [comment] 2021-01-09 18:26
Unfortunately I am not able to do much here as it's a Google Translate issue. I tried out wrapping both the content and ellipsis in spans (as suggested as a possible workaround) and that worked in terms of actually rendering something in Google Translate, but I won't be adding that to the library as it adds unnecessary/potentially unwanted HTML tags into the page, potentially breaking styling.
But it's something users can do themselves for both the content and ellipsis (ellipsis prop) if they want to.

Another solution for the time being (until the issue is fixed by GT team) would be ignoring these errors by monkeypatching removeChild/insertBefore facebook/react#11538 (comment)

**Closed by patrik-piskay** 2021-01-09 18:26 UTC
